on:
  workflow_dispatch:
  push:
    paths:
      - '**.js'
      - '**.mjs'
      - '**.cjs'
      - '**.jsx'
      - '**.ts'
      - '**.mts'
      - '**.cts'
      - '**.tsx'
      - '**.vue'
      - '**.json'
  pull_request:
    paths:
      - '**.js'
      - '**.mjs'
      - '**.cjs'
      - '**.jsx'
      - '**.ts'
      - '**.mts'
      - '**.cts'
      - '**.tsx'
      - '**.vue'
      - '**.json'

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.3.1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: pnpm install
      - run: pnpm lint

